package com.forum.bean;

// Generated 2010-5-2 20:02:19 by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Forum generated by hbm2java
 */
public class Forum {

	private long id;
	private String name;
	private String moderatorName;
	private String description;
	private long topicNum;
	private long replyNum;
	private Integer order;
	private Integer todayTopicNum;
	private String lastPostTopicName;
	private String lastPostAuthorName;
	private Timestamp lastPostDate;
	private Forum parent;
	private User moderator;
	private Set<Topic> topics = new HashSet<Topic>(0);
	private Set<Forum> children = new HashSet<Forum>(0);

	public Forum() {
	}

	public Forum(String name, String moderatorName, String description, long topicNum, long replyNum, Integer order, Integer todayTopicNum, String lastPostTopicName, String lastPostAuthorName,
			Timestamp lastPostDate, Forum parent, User moderator, Set<Forum> children) {
		this.name = name;
		this.moderatorName = moderatorName;
		this.description = description;
		this.topicNum = topicNum;
		this.replyNum = replyNum;
		this.order = order;
		this.todayTopicNum = todayTopicNum;
		this.lastPostTopicName = lastPostTopicName;
		this.lastPostAuthorName = lastPostAuthorName;
		this.lastPostDate = lastPostDate;
		this.parent = parent;
		this.moderator = moderator;
		this.children = children;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public Set<Topic> getTopics() {
		return topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModeratorName() {
		return this.moderatorName;
	}

	public void setModeratorName(String moderatorName) {
		this.moderatorName = moderatorName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getTopicNum() {
		return this.topicNum;
	}

	public void setTopicNum(long topicNum) {
		this.topicNum = topicNum;
	}

	public long getReplyNum() {
		return this.replyNum;
	}

	public void setReplyNum(long replyNum) {
		this.replyNum = replyNum;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Integer getTodayTopicNum() {
		return this.todayTopicNum;
	}

	public void setTodayTopicNum(Integer todayTopicNum) {
		this.todayTopicNum = todayTopicNum;
	}

	public String getLastPostTopicName() {
		return this.lastPostTopicName;
	}

	public void setLastPostTopicName(String lastPostTopicName) {
		this.lastPostTopicName = lastPostTopicName;
	}

	public String getLastPostAuthorName() {
		return this.lastPostAuthorName;
	}

	public void setLastPostAuthorName(String lastPostAuthorName) {
		this.lastPostAuthorName = lastPostAuthorName;
	}

	public Timestamp getLastPostDate() {
		return this.lastPostDate;
	}

	public void setLastPostDate(Timestamp lastPostDate) {
		this.lastPostDate = lastPostDate;
	}

	public Forum getParent() {
		return this.parent;
	}

	public void setParent(Forum parent) {
		this.parent = parent;
	}

	public User getModerator() {
		return this.moderator;
	}

	public void setModerator(User moderator) {
		this.moderator = moderator;
	}

	public Set<Forum> getChildren() {
		return this.children;
	}

	public void setChildren(Set<Forum> children) {
		this.children = children;
	}

}
