package com.forum.bean;
// Generated 2010-5-2 20:02:19 by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;

/**
 * Reply generated by hbm2java
 */
public class Reply  implements java.io.Serializable {


     private long id;
     private String content;
     private Timestamp postTime;
     private String authorName;
     private Integer floor;
     private User author;
     private Topic topic;

    public Reply() {
    }

    public Reply(String content, Timestamp postTime, String authorName, Integer floor, User author, Topic topic) {
       this.content = content;
       this.postTime = postTime;
       this.authorName = authorName;
       this.floor = floor;
       this.author = author;
       this.topic = topic;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Timestamp getPostTime() {
        return this.postTime;
    }
    
    public void setPostTime(Timestamp postTime) {
        this.postTime = postTime;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Integer getFloor() {
        return this.floor;
    }
    
    public void setFloor(Integer floor) {
        this.floor = floor;
    }
    public User getAuthor() {
        return this.author;
    }
    
    public void setAuthor(User author) {
        this.author = author;
    }
    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }




}


