package com.forum.bean;
// Generated 2010-5-2 20:02:19 by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic  implements java.io.Serializable {


     private long id;
     private String subject;
     private String content;
     private String authorName;
     private Timestamp postTime;
     private long replyNum;
     private long viewNum;
     private Forum forum;
     private User author;
     private Timestamp lastReplyTime;
     private Set<Reply> replies = new HashSet<Reply>(0);

    public Topic() {
    }

    public Topic(String subject, String content, String authorName, Timestamp postTime, long replyNum, long viewNum, Forum forum, User author, Timestamp lastReplyTime, Set<Reply> replies) {
       this.subject = subject;
       this.content = content;
       this.authorName = authorName;
       this.postTime = postTime;
       this.replyNum = replyNum;
       this.viewNum = viewNum;
       this.forum = forum;
       this.author = author;
       this.lastReplyTime = lastReplyTime;
       this.replies = replies;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Timestamp getPostTime() {
        return this.postTime;
    }
    
    public void setPostTime(Timestamp postTime) {
        this.postTime = postTime;
    }
    public long getReplyNum() {
        return this.replyNum;
    }
    
    public void setReplyNum(long replyNum) {
        this.replyNum = replyNum;
    }
    public long getViewNum() {
        return this.viewNum;
    }
    
    public void setViewNum(long viewNum) {
        this.viewNum = viewNum;
    }
    public Forum getForum() {
        return this.forum;
    }
    
    public void setForum(Forum forum) {
        this.forum = forum;
    }
    public User getAuthor() {
        return this.author;
    }
    
    public void setAuthor(User author) {
        this.author = author;
    }
    public Timestamp getLastReplyTime() {
        return this.lastReplyTime;
    }
    
    public void setLastReplyTime(Timestamp lastReplyTime) {
        this.lastReplyTime = lastReplyTime;
    }
    public Set<Reply> getReplies() {
        return this.replies;
    }
    
    public void setReplies(Set<Reply> replies) {
        this.replies = replies;
    }




}


