package com.forum.bean;
// Generated 2010-5-2 20:02:19 by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private long id;
     private String username;
     private String password;
     private String nickName;
     private Boolean active;
     private Timestamp registerTime;
     private String activeString;
     private String email;
     private Set<Topic> topics = new HashSet<Topic>(0);
     private Set<Reply> replies = new HashSet<Reply>(0);
     private Set<Forum> forums = new HashSet<Forum>(0);

    public User() {
    }

    public User(String username, String password, String nickName, Boolean active, Timestamp registerTime, String activeString, String email, Set<Topic> topics, Set<Reply> replies, Set<Forum> forums) {
       this.username = username;
       this.password = password;
       this.nickName = nickName;
       this.active = active;
       this.registerTime = registerTime;
       this.activeString = activeString;
       this.email = email;
       this.topics = topics;
       this.replies = replies;
       this.forums = forums;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Timestamp getRegisterTime() {
        return this.registerTime;
    }
    
    public void setRegisterTime(Timestamp registerTime) {
        this.registerTime = registerTime;
    }
    public String getActiveString() {
        return this.activeString;
    }
    
    public void setActiveString(String activeString) {
        this.activeString = activeString;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Topic> getTopics() {
        return this.topics;
    }
    
    public void setTopics(Set<Topic> topics) {
        this.topics = topics;
    }
    public Set<Reply> getReplies() {
        return this.replies;
    }
    
    public void setReplies(Set<Reply> replies) {
        this.replies = replies;
    }
    public Set<Forum> getForums() {
        return this.forums;
    }
    
    public void setForums(Set<Forum> forums) {
        this.forums = forums;
    }




}


